name: Build & Deploy Phoenix

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      MIX_ENV: prod
    outputs:
      image-tag: ${{ steps.set_tag.outputs.tag }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Elixir & Erlang
        uses: erlef/setup-elixir@v1
        with:
          otp-version: "25.x"
          elixir-version: "1.14.x"

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20.x"
          cache: "npm"

      - name: Fetch Elixir deps
        run: mix deps.get --only prod

      - name: Install NPM deps
        run: npm install --prefix assets

      - name: Setup & build assets
        run: |
          mix assets.setup    # installs tailwindcss/esbuild if missing
          mix assets.deploy   # runs tailwind gate_rush --minify, esbuild gate_rush --minify, phx.digest

      - name: Build release
        run: mix release

      - name: Set image tag
        id: set_tag
        run: echo "tag=${GITHUB_SHA::8}" >> $GITHUB_OUTPUT

  docker:
    needs: build
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - uses: actions/checkout@v3

      - uses: docker/setup-buildx-action@v2

      - uses: docker/login-action@v2
        with:
          registry: ${{ secrets.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build & push image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ secrets.DOCKER_REGISTRY }}/${{ github.repository_owner }}/myapp:${{ needs.build.outputs.image-tag }}

  deploy:
    needs: docker
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: Trigger Coolify via Official Action
        uses: themarkwill/coolify-actions@v0.0.3
        with:
          coolify-url: ${{ secrets.COOLIFY_URL }}
          coolify-app-id: ${{ secrets.COOLIFY_APP_ID }}
          coolify-token: ${{ secrets.COOLIFY_TOKEN }}
