name: Build & Deploy Phoenix

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: prod
    outputs:
      image-tag: ${{ steps.meta.outputs.tag }}
    steps:
      - uses: actions/checkout@v3

      - uses: erlef/setup-elixir@v1
        with:
          otp-version:    '26.x'
          elixir-version: '1.18.x'

      - name: Install deps & build assets
        run: |
          mix deps.get
          cd assets && npm ci && npm run deploy && cd ..
          MIX_ENV=prod mix compile phx.digest

      - name: Build release
        run: MIX_ENV=prod mix release

      - name: Set image tag
        id: meta
        run: echo "tag=${GITHUB_SHA::8}" >> $GITHUB_OUTPUT

  docker:
    needs: build
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - uses: actions/checkout@v3

      - uses: docker/setup-buildx-action@v2

      - uses: docker/login-action@v2
        with:
          registry: ${{ secrets.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build & push image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ secrets.DOCKER_REGISTRY }}/${{ github.repository_owner }}/myapp:${{ needs.build.outputs.image-tag }}

  deploy:
    needs: docker
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: Trigger Coolify via Official Action
        uses: themarkwill/coolify-actions@v0.0.3
        with:
          coolify-url:    ${{ secrets.COOLIFY_URL }}
          coolify-app-id: ${{ secrets.COOLIFY_APP_ID }}
          coolify-token:  ${{ secrets.COOLIFY_TOKEN }}
